<?php

namespace Database\Seeders\Compositions\Home;

use Illuminate\Support\Facades\DB;

trait HasBackgroundsCategoryData
{
    public function insertBackgroundsItemsData()
    {
        $this->currentOrder = 1;

        DB::table('home_items')->insert([
            $this->buildItemStructure(null, '/assets/images/home/items/GKQVS9q.png', 'Default Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/4YXmogn.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/qbyTAoY.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/WmMizPc.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/KzH3oMY.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/Cy0iNm6.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/2upZxv2.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/s1LaSNl.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/M9y5naT.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/2lcQLNG.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/4ttdDzg.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/WDoPNEU.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/pu7hsA7.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/SRDeAkG.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/zUFEmB8.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/fA4RzU4.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/oTQK04v.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/p3TCdHt.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/BDusXRR.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/7GQztPu.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/qlaPRp1.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/CLNktLz.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/Dpd8dbY.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/sasbTZw.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/d20NpV2.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/3nprL2K.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/rD4nz0K.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/dwJRNTj.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/6WAOJJt.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/FRAVwyT.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/xPSwZyB.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/fGhQYyF.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/Tqd16xU.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/JLabJgR.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/5cXYkVf.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/yr3YhkO.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/qAOsIa0.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/Uk9y8WX.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/o9MOw2S.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/vbYrPGC.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/0WoPTDe.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/lAq6Ned.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/pFkBf1O.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/L1g3V67.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/825ketL.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/gV1gC4M.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/3wCU3Wx.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/4Wu7iND.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/FKzxkUI.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/4SCpOfo.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/zCLwpW7.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/L1TOmig.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/iYf1XFH.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/hB24oKS.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/2JGGQIT.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/fVuef0j.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/LrCPUS1.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/SbUzEZp.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/5aumTlj.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/aNksAYc.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/LOo9i4G.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/1oRGzbx.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/c9AR3tx.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/NnSd72y.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/XD9yXeS.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/drRUaNk.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/Gv3NUv7.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/4uYg7yr.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/TMPhfzW.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/2NUdWgI.png', 'Home Background', 15, 'b'),
            $this->buildItemStructure(null, '/assets/images/home/items/CoeD0M0.png', 'Home Background', 15, 'b'),
        ]);
    }
}
