    name: Laravel

    on:
      push:
        branches: [ "main", "dev" ]
      pull_request:
        branches: [ "main", "dev" ]

    jobs:
      tests:
        runs-on: ubuntu-latest
        
        services:
          mariadb:
            image: mariadb:11
            env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: atomcms_testing
            ports:
              - 3306:3306
            options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1

        - name: Cache composer dependencies
          uses: actions/cache@v4
          with:
            path: vendor
            key: composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              composer-

        - name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.4

        - name: Install composer dependencies
          run: |
            composer install --no-scripts

        - name: Install NPM dependencies
          run: npm install

        - name: Compile assets
          run: npm run build:atom

        - name: Prepare Laravel Application
          run: |
            cp .env.testing.example .env.testing
            php artisan key:generate --env=testing
            
        - name: Setup Database Schema
          run: |
            php artisan migrate --force --env=testing

        - name: Run Test suite
          run: php artisan test --env=testing
